### ISSUE TITLE
SubsitesVirtualPage has_one / has_many relations not available

### ISSUE THREAD

**Issue by sebastiand** [silverstripe/silverstripe-subsites#128]
When using a SubsitesVirtualPage referencing a custom Page with has_one or has_many relations, I can't access these relations in the template.

Only db fields are available. Even the IDs of the relations aren't available...

Does anyone know where to extend the function calls? Maybe just passing them on to the original Page would work...

**Comment by chasevida** [comment]
Like so many of the SilverStripe threads, there are just no answers or responses. I've worked some seriously funky code to get around the flaky `SubsitesVirtualPage` inheritance issues. Did you ever get an official solution for this?

**Comment by liquidedge** [comment]
This issue is making the Subsites module virtually unusable for us. Very frustrating. Hope there is a solution provided soon.

**Comment by tractorcow** [comment]
VirtualPage has been re-written extensively in 4.0, in ways which we couldn't safely do in 3.x without breaking backwards compatibility. Once this is stable and we have upgraded subsites for 4.0 support, I would expect this issue to be resolved.

**Comment by robbieaverill** [comment]
I've quickly tested this by using a page in Subsite A that has content blocks in it (a has_many with nested has_many relations), and creating a virtual page in Subsite B that points to it. The page in Subsite B renders as I would expect it to (the same as in Subsite A), so I think @tractorcow's assumption that this would be fixed with SS 4.0 is correct as far as I can tell.

@chasevida I'm sorry we didn't provide any feedback on this issue sooner.

Let us know if anyone experiences issues with this running SilverStripe 4 and we can reopen if necessary.
