### ISSUE TITLE
Image upload into editor field not working

### ISSUE THREAD

**Issue by acndr** [silverstripe/silverstripe-subsites#168]
When uploading an image into the content field / HTMLEditorField, the upload field throws and error (in firebug):

TypeError: settings.headers is undefined
opts = {pjax: xhr.getResponseHeader('X-Pjax') ? xhr.getResponseHeader('X-Pjax') ...

And also the uploaded image doesn't show below the uploader after its finished
The image is uploading though as I can see it in Files

SS version 3.1.6

**Comment by tomys** [comment]
same problem here.
TypeError: settings.headers is undefined in LeftAndMain.js line 134.

I have one subsite (not the main site) where i can insert images without problems.
On all other subsites i can not insert a image.

At the subsites where i can NOT insert a image, have to click twice the image in the "insert media" dialog to select the image. At the subsite where it works, i must only click once to select the image.

After the selection an press "insert" (transl. from german) the image are display in the HTMLEditor Windows. If i click save or save&exit the HomePage gets the focus in the sitetree and the image was not saved in the Html content.

**Comment by infinitorium** [comment]
Hi, 
Just reporting the same issue, we've done a debugging at this point. The HTMLEditorField_Toolbar::viewfile() function is supposed to be called at this point, and the request is being made (as indicated in Chrome's developer tools) but it returns an zero byte response. Viewfile is never even reached. We are doing some more debugging as it's a causing a client grief so will submit a pull request if we manage to find a solution.

**Comment by dhensby** [comment]
Thanks @infinitorium, that'd be great and really appreciated

**Comment by infinitorium** [comment]
Hi again,

So I located the issue and have figured out a fairly hacky fix, I am not sure if it would be suitable for a pull request but it is something temporary that can be used. I spent ages debugging this but I'll cut my long story short. 

The root of the cause was in LeftAndMainSubsites::onBeforeInit(), on line 236. LeftAndMain::currentPage is called to check if the subsite needs to be changed for the request. LeftAndMain::currentPage returns a SiteTree object based on the ID that is requested - however we are requesting a File. LeftAndMainSubsites::onBeforeInit() performs some checks and the uses LeftAndMainSubsites::shouldChangeSubsites() to determine that the subsite needs to be changed to view the SiteTree object (if one exists) for the request ID. This started a loop of failing checks everytime we try to call HTMLEditorField_Toolbar::viewfile().

The fix I put in place was to created a custom subclass of the LeftAndMainSubsites and overload shouldChangeSubsites() so that it returns false if 'viewfile' is the ID param of the url (the action is EditorToolbar). This seems to solve the issue but is a pretty icky fix.

**Comment by dhensby** [comment]
@tractorcow what do you think to this?

**Comment by tractorcow** [comment]
Nothing immediately... it seems like a weird bug I'd have to dig into subsites to really understand. Until now I've managed to avoid having to look too deply into the code of this module. :)

**Comment by tomys** [comment]
@infinitorium 
Can you please tell me the details of your fix.
This problem actually prevents the go live in our sports-community website.

**Comment by infinitorium** [comment]
Hi @tomys 

Here is a gist with the fix I applied:
https://gist.github.com/infinitorium/d5087ade252568cf3a3f

Its a subclass which is applied via Object::useCustomClass

**Comment by jyrkij** [comment]
I can confirm this still exists... We've come accross this in at least one of our client projects. Here's the fix I ended applying based on @infinitorium's detective work:

Relevant `Injector` configuration:

```yml
Injector:
  LeftAndMainSubsites:
    class: LeftAndMainSubsitesWithFixedImageUpload
```

And the class:

```php
class LeftAndMainSubsitesWithFixedImageUpload extends LeftAndMainSubsites
{
    public function shouldChangeSubsite(
        $adminClass,
        $recordSubsiteID,
        $currentSubsiteID
    ) {
        /** @var SS_HTTPRequest $request */
        $request = $this->owner->getRequest();
        $id = $request->param('ID');
        if ($id === 'viewfile') {
            return false;
        } else {
            return parent::shouldChangeSubsite(
                $adminClass,
                $recordSubsiteID,
                $currentSubsiteID
            );
        }
    }
}
```

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
