### ISSUE TITLE
SiteTree canEdit checks for access to CMSMain

### ISSUE THREAD

**Issue by webtorque7** [silverstripe/silverstripe-subsites#170]
The subsites module prevents access to SiteTree objects unless the user has access to CMSMain, even though there is separate content permissions to view/edit etc. This effects other modules which allow editing SiteTree objects without using CMSMain and rely on the canEdit function for permissions.

My use case is I'm specifically denying access to CMSMain for certain user groups, providing a simplified method for them to access and edit just the content they need to. The group is set up with permissions to view/edit any page, but canEdit fails due to the check to CMSMain.

**Comment by robbieaverill** [comment]
Hi @webtorque7, thanks for reporting. I'm going to close this issue due to inactivity. If you're still experiencing a bug with this, please feel free to reopen.

As an aside, restricting access in the CMS is actually non-trivial due to the way that extensions work in checking these permissions. That is to say that it's easy to _allow_ access for groups to do something, but it's harder to _restrict_ access in some cases. I suspect you may be finding this issue here too.
