### ISSUE TITLE
Subsite Virtual Page won't use subsites template

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-subsites#235]
Recently the subsite module stopped using templates specified by the Subsite Virtual Page. For example with the following site structure: 

themes/maintheme/Layout/MyPageType.ss
themes/mysubsite/Layout/MyPageType.ss

A subsiteVirtualPage with the linked page of MyPageType.php will be rendered with the Page.ss of mysubsite, instead of MyPageType.ss

**Comment by tractorcow** [comment]
Added to the big bag of "virtual page issues to fix"

**Comment by dhensby** [comment]
@torleif have you PR-ed your commit?

**Comment by torleif** [comment]
@dhensby PR-ed?

**Comment by dhensby** [comment]
Pull request. Did you open a pill request with the commit that references this issue?

**Comment by torleif** [comment]
@dhensby nope, i'll do that now

**Comment by robbieaverill** [comment]
Do we need an epic type holder issue for virtual page bugs?

**Comment by robbieaverill** [comment]
Assuming this still affects v4, I'm retagging

**Comment by robbieaverill** [comment]
I can't reproduce this on SilverStripe 4.4.x with Subsites 2.3.x. I used the CWP starter and watea themes, where my subsite has watea configured and starter contains silverstripe/blog page templates where watea doesn't. The virtual page correctly uses the starter blog page templates, rather than reverting to a Page template (which watea _does_ contain).

Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
