### ISSUE TITLE
User notice after changing settings

### ISSUE THREAD

**Issue by spekulatius** [silverstripe/silverstripe-subsites#244]
Hello,

I'm building a site using the CWP recipe and I found an issue with the subsites module. My starting point is:

* Site has no subsites at the current state.
* Logged in as a user with restricted permissions, allowed to access the backend, but has only permissions for a particular model admin.
* Access to the backend works, including the model admin.

The problem comes up after changing the following setting in the security section to "Only these sites":

![setting](https://cloud.githubusercontent.com/assets/8433587/14516212/e000c2f0-0254-11e6-831c-6d48a697087b.png)

The user with the restricted access will get this error when attempting to access the CMS:

![error](https://cloud.githubusercontent.com/assets/8433587/14516294/a10db3cc-0255-11e6-8183-23c9e1b0cedf.png)

This happens with existing as well as new sessions for the user in question.

Expected behaviour:

- No change expected as there aren't any subsites to restrict the access to.

some used packages with versions:
- silverstripe/cms 3.3.1
- silverstripe/framework 3.3.1
- silverstripe/subsites 1.2.1
- cwp/cwp 1.3.0 
- cwp/cwp-core 1.3.0
- cwp/cwp-recipe-basic 1.3.0
- cwp/cwp-recipe-basic-dev 1.0.7

Has anyone else identified this problem? Maybe even has a solution.

Cheers,
Peter

**Comment by tractorcow** [comment]
This is a bug in CWP; Specifically to do with BasePage_Controller::init(). This seems to occur when rendering ErrorPage in the same PHP thread as another page is being rendered.

What would happen otherwise is that you'd receive an error message (probably about a security notice you're not allowed to view something). Instead the error page causes this error.

Maybe there's a fix we could add to requirements, so that there isn't a single global 

In any case, I suggest you raise this with the service desk https://www.cwp.govt.nz/service-desk/ since it's a problem in the recipe specifically. Maybe we just don't include these scripts on error pages.

**Comment by spekulatius** [comment]
Hello @tractorcow 

Thanks for coming back to me on this. I have raised this with the service desk.

Cheers,
Peter

**Comment by tractorcow** [comment]
Thanks @spekulatius , hope they can help you out. :D At least you're getting someone who HAS to help you to fix it hehe.
