### ISSUE TITLE
Query in model/Subsite.php wrong

### ISSUE THREAD

**Issue by DzKerr** [silverstripe/silverstripe-subsites#253]
Hi,

I have just discovered something weird in the `mycode/model/Subsite.php`, function `getSubsiteIDForDomain`. The query is not good at all!

``` php
$matchingDomains = DataObject::get(
                "SubsiteDomain",
                "'$SQL_host' LIKE replace(\"SubsiteDomain\".\"Domain\",'*','%')",
                "\"IsPrimary\" DESC"
            )->innerJoin('Subsite', "\"Subsite\".\"ID\" = \"SubsiteDomain\".\"SubsiteID\" AND \"Subsite\".\"IsPublic\"=1");
```

As you know it is the **field** first then the value ([documentation](http://www.w3schools.com/sql/sql_like.asp))  

I fix this problem using this correction : 

``` php
            $matchingDomains = DataObject::get(
                "SubsiteDomain",
                "\"SubsiteDomain\".\"Domain\" LIKE replace('$SQL_host','*','%')",
                "\"IsPrimary\" DESC"
            )->innerJoin('Subsite', "\"Subsite\".\"ID\" = \"SubsiteDomain\".\"SubsiteID\" AND \"Subsite\".\"IsPublic\"=1");
```

Which it works in my website.  
What are you thinking about it ?

**Comment by dhensby** [comment]
`replace('$SQL_host','*','%')",`

if `$SQL_host` is a PHP variable, we can do the replacement in PHP rather than have the DB server make the change

**Comment by DzKerr** [comment]
Ok for sure, but it is not the main problem ^^

**Comment by tractorcow** [comment]
```php
$host = str_replace('*', '%', $host);
SubsiteDomain::get()->filter('SubsiteDomain:PartialMatch', $host);
```

And don't do any SQL escaping at all.

**Comment by robbieaverill** [comment]
Still affects v4

**Comment by robbieaverill** [comment]
The suggested fixes here won't work, because `$host` is a request hostname e.g. `sub.domain.com`, and the `LIKE replace('$SQL_host','*','%')"` part of the query is replacing `*.domain.com` with `%.domain.com` in the database before it performs a partial match against it the provided `$host` variable.

Closing as #wontfix - it's not the prettiest piece of code, but it's working the way it needs to.

**Comment by NightJar** [comment]
@DzKerr I'd like to take a moment to thank you for this suggestion, however I fear that this is once again a case of the infamous w3schools distributing misleading information.

I'd also like to say sorry it's taken over two years to get this feedback.

The [link](https://www.w3schools.com/sql/sql_like.asp) you've provided with the issue does indeed list the `LIKE` operator to be used as `columnN LIKE pattern`
However while this is technically correct, it is not the whole story.
The LIKE clause is more correctly stated as being `expression LIKE pattern`, where any valid SQL can form the `expression` or `pattern`, so long as it evaluates to a `string` - such as a directly declared string primitive.
This is true for [MySQL](https://dev.mysql.com/doc/refman/5.6/en/string-comparison-functions.html#operator_like), [Postgre](https://www.postgresql.org/docs/8.3/static/functions-matching.html), and [SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-2017&viewFallbackFrom=sql-server-2014) (and I'm sure all others).

No matter the way one defines the expression or pattern, the eventual (matching) evaluation should look something like `some.host LIKE %.some.host`

---

The critical reason why your suggested fix would not be accepted (although it worked for you), is likely because the subsite domain you tested with did _not_ contain a wildcard character.
Let's compare:

- A `SubsiteDomain` defined as `subsite.yourhost.test`
- A request loading over `subsite.yourhost.test`

Using the version released immediately before this issue was opened: [v`1.2.3`](https://github.com/silverstripe/silverstripe-subsites/blob/1.2.3/code/model/Subsite.php#L184)
The query fragment will (effectively) become `'subsite.yourhost.test' LIKE 'subsite.yourhost.test'`
Where your suggested fix will result in `'subsite.yourhost.test' LIKE 'subsite.yourhost.test'`
I.e. exactly the same :)

However, lets consider the use of wild cards:

- A `SubsiteDomain` defined as `*.myhost.test`
- A request loading over `anysubsite.myhost.test`

Still using [v`1.2.3`](https://github.com/silverstripe/silverstripe-subsites/blob/1.2.3/code/model/Subsite.php#L184)
The query fragment will become `'anysubsite.myhost.test' LIKE '%.myhost.test'` which will match.
Where as your suggestion will result in `'*.myhost.test' LIKE 'anysubsite.myhost.test'` which will **not** match.

---

As @robbieaverill pointed out above, this can't really be tidied up because unfortunately it isn't possible to create such a query where we manipulate a _column_ as an argument to a filter - the ORM doesn't directly support this sadly. It could be achieved via some complex manipulation of the SilverStripe query object in PHP before it is dispatched to the database, however I fear the code would be much more ugly that what is already in place (now [v`2.1.1`](https://github.com/silverstripe/silverstripe-subsites/blob/2.1.1/src/Model/Subsite.php#L286-L294)):
https://github.com/silverstripe/silverstripe-subsites/blob/bf2c81dce62ae9a7623d224fd31a39505260eb57/src/Model/Subsite.php#L286-L294
