### ISSUE TITLE
Option to run multiple sites / subsites without theme (theme-less)

### ISSUE THREAD

**Issue by johanchristian** [silverstripe/silverstripe-subsites#261]
Selecting a theme is currently mandatory, when adding a new subsite.
Can we please have the option to make this optional?

Thank you.

**Comment by robbieaverill** [comment]
## Scenarios

### No themes installed

As a CMS user,
Given that I have no themes installed,
And I add a subsite,
I expect not to see a Theme dropdown,
So my user interface is not unnecessarily cluttered

### One or more themes installed

As a CMS user,
Given that I have one or more themes installed,
And I add a subsite,
I expect to see a Theme dropdown,
And I expect it to have an empty option,
So that I can either choose a theme or not

**Comment by robbieaverill** [comment]
Fixed in #273
