### ISSUE TITLE
Preview panel breaking /admin section on SubSite when viewing Mainsite

### ISSUE THREAD

**Issue by brettt89** [silverstripe/silverstripe-subsites#263]
If you access the /admin section of a subsite, then change the Site to "Main Site". When trying to edit a page the preview panel causes the CMS to redirect to a broken page.

Replication:
- Login to /admin of subsite
- Change site being edited to "Main Site"
- Select a page to edit on the Main Site.

**Comment by adrexia** [comment]
We've just encountered this too. Though we don't normally get the redirect bit. 

Our replication steps:

1. I log in via the subsite domain (e.g subsite.mydomain.com)
2. I switch to the main site (mydomin.com) 
3. I open a page in sitetree and look at the url/preview

Expected: the url will match the main site (mydomin.com)  and show the preview of that site
Actual: the url matches the subsite I logged in under (subsite.mydomain.com) and the preview tries to show that site instead (sometimes successfully)

**Comment by clarkepaul** [comment]
**Also a client on CWP has raised the issue**

The case is happening in the following situations:
An editor is editing several subsites in the same instance
They are using the preview feature to send links to their stakeholders

A preview link only works if it has the sub-site complete URL. However, when changing subsites in the backend, the preview URL still has the first site, so the generated preview link doesn’t work.

When changing subsites in the backend, the preview should update the URL to match the URL of the subsite.

**Comment by clarkepaul** [comment]
Might be related somehow? https://github.com/tractorcow/silverstripe-fluent/issues/144

**Comment by adrexia** [comment]
@clarkepaul  I don't think that's related, though it might have a similar cause. In our case I believe the cause is that we never define urls for the main site in a subsites setup. The urls are all generated in the main site via the base url. If you log in via a subsite the base url will be the domain of the subsite you logged in under.  

FWIW, our issue was reported on behalf of a CWP client too.

**Comment by raissanorth** [comment]
When I looked into this I could reproduce the issue as described using:
```
silverstripe/framework             4.1.2        
silverstripe/cms                   4.1.2 
silverstripe/subsites              2.1.0      
```

I added a local subdomain. I logged into the subsite matching that domain, then switched to the main site. The preview for any page belonging to the latter was not available. 

--------
The only changes I made since then were adding a base url constant to my `.env` and later removing it. 

However, after making that change (any reverting it), I cannot reproduce the issue anymore. 

To the contrary, when following the same steps as described above, all page previews for anything belonging to a main site or subsite render as expected. Furthermore, even when using the subsite domain to login, the main site is shown in the CMS. Also, the preview url always has the subsite domain prepended to it, but when opened shows the main site. 

![image.png](https://images.zenhubusercontent.com/5a16269b8a75884b9088859e/55dcab6b-7f08-4f86-98b7-6d8a6d3adbdd)

**Comment by NightJar** [comment]
Could it be Session related @raissanorth ?

**Comment by NightJar** [comment]
PR @ #374

**Comment by adrexia** [comment]
@NightJar your PR fixes preview specifically, but does it update the rendered url in the page edit form too?

**Comment by NightJar** [comment]
@adrexia No it doesn't - but I think it won't and I'll split that into a separate issue :)

**Comment by NightJar** [comment]
@adrexia https://github.com/silverstripe/silverstripe-subsites/issues/376 :)
