### ISSUE TITLE
Site settings tab confusing while using subsites

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-subsites#283]
Not sure if this belongs on [site settings](https://github.com/silverstripe/silverstripe-siteconfig).

When you install subsites, you get an extra subsite tab in the CMS:

![image](https://user-images.githubusercontent.com/67215/27567602-e50fb79c-5b40-11e7-892f-138f184ede39.png)

Some of the settings for each subsite is under the subsite tab, while others are on the settings tab. You have to change to that subsite in the top left dropdown to edit the settings in the settings tab. 

It would be less confusing and cluttered if the site settings tab was hidden if the subsite module is installed. This way you could edit the site settings via the subsite tab. 

This might be easier with SilverStripe 4.0 as you could potentially hide the siteconfig module disabled if the subsite module is installed, or disable able it with a yml config.

**Comment by torleif** [comment]
@robbieaverill would anyone be adverse if I made a PR that made it look similar to the following in SS 4.0?

![mockup](https://user-images.githubusercontent.com/67215/30625262-4cece822-9e16-11e7-9c9f-1670d2cc0eb2.png)

**Comment by wilr** [comment]
@torleif I think there would as the left hand menu is filtered by subsite I would recommend keeping the dropdown on the top left

**Comment by wilr** [comment]
@torleif Perhaps remove the theme option from the subsites admin, and just use `SiteConfig`.

**Comment by robbieaverill** [comment]
Yeah, since subsite separation doesn't only apply to Pages I don't think this UI change would be justified. We'd need to replicate this throughout anything that the subsite extension was applied to, which could get confusing over time.

As for the original point about the site settings, it could also be risky to remove the tab if subsites is installed since other modules may expect to be able to push settings to it within its original context - this might also get confusing if subsites had to replicate the structure in another area.

I think the idea behind the LHS dropdown is that it's adding a single point of context switching in the CMS, and the user can continue to assume that everything else in the CMS will remain unchanged while still being separated by the chosen subsite.

Going to close for now - feel free to reopen if you have a strong justification for change :)

**Comment by torleif** [comment]
@robbieaverill thanks for your feedback. My primary concern is that our CMS admins find this approach very confusing. For example, if you're in a subsite, where did the reports go? The context in which the user is in makes absolutely no sense at all - Pages and Settings are unique to the subsite; but Files, Security, Reports, Subsites, and Help are not. There is no indication to the user this is the case, and in many instances has caused data to be written to places it shouldn't have. It's bad UI as it causes information to be overwritten because of its inconsistency. 

I feel this goes against the SilverStripe ethos of keeping it simple.

From a developers perspective, this is also a nightmare. The logic that applies the context of the subsite is broken and overly complex. For example giving someone rights that applies to only a subsite is possible, but has to be done on that subsite, on a tab that is global, but depending on the permissions often locks someone out of the CMS entirely. Sometimes it will give them admin access to the whole site, even when no admin rights are given. By avoiding the context being applied, it will help avoid this problem entirely. 

My original issue was created in the hopes of taking baby step towards addressing a core underlying problem with the subsites module. But they are two separate issues.

**Comment by robbieaverill** [comment]
Hey @torleif 

>Pages and Settings are unique to the subsite; but Files, Security, Reports, Subsites, and Help are not

Subsites provides an extension for files and security groups as well as pages and settings

>For example giving someone rights that applies to only a subsite is possible, but has to be done on that subsite, on a tab that is global, but depending on the permissions often locks someone out of the CMS entirely. Sometimes it will give them admin access to the whole site, even when no admin rights are given. By avoiding the context being applied, it will help avoid this problem entirely.

Do you know if these issues have been raised on this repository yet?

---

I like the idea of improving the user experience here, especially since you've highlighted that you and your colleagues find the current UI difficult to use. I'm not sure that the original idea is appropriate in the meantime, but maybe we should raise a new issue for assessing ways that we can improve the UX for subsites?

**Comment by wernerkrauss** [comment]
It's a feature that you can enable each (Model)Admin for all sites, not a bug.

TBH this confused me the first time, but maybe you want a ModelAdmin only for "main" or a special subsite. 

In SS3 you can add any Modeladmin to all Subsites using an extension, like:

```
MyCoolModelAdmin:
  extensions:
    - SubsiteMenuExtension
``` 
If you need more fancy logic on which Subsite your admin should be shown create a method called  subsiteCMSShowInMenu() which checks if all conditions are given and returns a boolean value.

Maybe this should go in docs?

See http://www.silverstrip.es/blog/subsites-show-modeladmin-in-backend-on-all-subsites/

**Comment by robbieaverill** [comment]
I just realised I never replied to this 😆 

If you're keen to make a documentation pull request that'd be awesome!
