### ISSUE TITLE
Add ability to disable Subsite Filtering in CLI

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-subsites#352]
E.g. when updating to SS4 you need to use `MigrateFileTask` . On a recent project I wondered why so many files are not converted, until I realised that Subsites filters the files, which is totally logical.

But running that task for each Subsite can be a bit of a pain...

```
vendor/bin/sake dev/tasks/MigrateFileTask
vendor/bin/sake dev/tasks/MigrateFileTask SubsiteID=1
vendor/bin/sake dev/tasks/MigrateFileTask SubsiteID=2
...
```

It would be great 

a) to document this behaviour more clearly
b) disable subsite filtering, e.g. by using `SubsiteID=-1` or `SubsiteFiltering=none` or with a yml config for each task

**Comment by NightJar** [comment]
Out of curiosity, what happens when you set `SubsiteID=0`?
I have a feeling it won't work... but... maybe worth a try?

**Comment by wernerkrauss** [comment]
@NightJar SubsiteID 0 is "Main Site"

**Comment by NightJar** [comment]
Ah yeah 😅

**Comment by robbieaverill** [comment]
In this particular case you could overload `FileMigrationHelper` with Injector and implement your own `Subsite::disable_subsite_filter()` calls around the original logic for `->run()`.

I've only had a quick look at this, but I don't think the framework's BuildTask API is mature enough to allow us to implement this feature at the moment. It would require before/after extensions at the very minimum (but that could only be implemented in `TaskRunner::runTask()`, not individual tasks). Ideally the BuildTask API would provide some sort of middleware approach when running the task, and there is already an open RFC to refactor it to use PSR-3 loggers for output interfaces.

I think for now this will be a "won't fix" - you can implement workarounds in order to migrate your files when upgrading the project, so it has limited impact.
