### ISSUE TITLE
SubsitesVirtualPage should allow extending via updateCMSFields

### ISSUE THREAD

**Issue by brandoniffert** [silverstripe/silverstripe-subsites#372]
I'm trying to write an extension for SubsitesVirtualPage and noticed that [`getCMSFields()`](https://github.com/silverstripe/silverstripe-subsites/blob/master/src/Pages/SubsitesVirtualPage.php#L41) does not offer an extension point for `updateCMSFields`, i.e.

`$this->extend('updateCMSFields', $fields)`

**Comment by dhensby** [comment]
`updateCMSFields` is called in the base method in `SiteTree`.

**Comment by brandoniffert** [comment]
Seems to act differently depending on where the extension point is. For example: if I currently try `$fields->removeByName('VirtualPageContentLinkLabel')` in my extension, it doesn't work. If I manually add the `$this->extend('updateCMSFields', $fields)` extension point in [`getCMSFields()`](https://github.com/silverstripe/silverstripe-subsites/blob/master/src/Pages/SubsitesVirtualPage.php#L41), it works.

**Comment by dhensby** [comment]
yes, but that will result in `updatCMSFields` being called twice. It doesn't work without your change because `updateCMSFields` is called before the logic in `SubsitesVirtualPage`.

This could be fixed if the module used `beforeUpdateCMSFields` (https://docs.silverstripe.org/en/4/developer_guides/extending/extensions/#extension-injection-points)

**Comment by brandoniffert** [comment]
Thanks for the clarification
