### ISSUE TITLE
URLSegment link should reflect Subsite's domain, not simply the domain the CMS was loaded on

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-subsites#376]
![image.png](https://images.zenhubusercontent.com/5a16269b8a75884b9088859e/55dcab6b-7f08-4f86-98b7-6d8a6d3adbdd)

It would be great if the domain for the subsite was to be used for the link circled on the right.

**Steps to reproduce:**
1. Install a site with the subsites module, on a local server e.g. `localhost`.
2. Create a Subsite named "Subsite". Assign `subsite.localhost` as the Domain.
3. Load `subsite.localhost/admin/pages`
4. Use the Dropdown in the CMS main menu (Left) to choose "Main Site" (instead of/switching away from "Subsite")
5. Choose to edit a page in the main site's site tree (e.g. `About Us`)
6. Notice the link to this page in the EditForm is `subsite.localhost/about-us` as opposed to `localhost/about-us`.

**Cautions:**
It is important to load the domain the CMS is loaded on in the preview panel as per #374 - otherwise one runs into issues with cross origin requests. However as the link on the EditForm is simply a link, this should reflect the domain the page is actually intended for.

Thanks to @raissanorth and @adrexia for pointing this out

**Comment by robbieaverill** [comment]
The problem with this is that the "main site" never has a domain given to it. When you access a subsite's admin interface it's running on that subsite's domain, so it's assuming the base URL of that subsite (which is defined).

We have no structured way to get the main site's domain. 

This could be fixed by not treating "main site" as an imaginary subsite but a concrete one that always exists, but otherwise I don't think we can fix this. I'm going to close it for now, but feel free to reopen if you feel strongly that it should be fixed.

**Comment by NightJar** [comment]
I feel like this could be worked around with documentation and `BASE_URL` being set (which I believe is overridden by `alternate_base_url` when running a subsite).
I've not looked into this though.
