### ISSUE TITLE
InitStateMiddleware prevent errors from showing up in dev/build and dev/tasks

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-subsites#377]
Using the latest stable version, with subsite module installed, if you have a DatabaseException, it will not show up in dev/build and dev/tasks/SomeTask.

Instead, it calls DevelopmentAdmin::index (not sure why)

Screenshot below
![migrate db values](https://user-images.githubusercontent.com/250762/42323526-c591af24-8060-11e8-8162-8f2ca7400960.png)

**Comment by ScopeyNZ** [comment]
I assume you also need `silverstripe/fluent` because `InitStateMiddleware` is part of fluent?

**Comment by NightJar** [comment]
SubsiteSate is a thing - https://github.com/silverstripe/silverstripe-subsites/blob/master/src/Middleware/InitStateMiddleware.php

Namespaces! @ScopeyNZ

**Comment by lekoala** [comment]
Yes, the specific steps are:

- install a fresh 4.1.2
- install the subsite module
- run a build task with an error, for instance : DB::query('DROP TABLE NotExistingTable')
- see how the DatabaseException is strangely handled

I believe it's the middleware that catch the DatabaseException and pass it to the delegate that does this, but I'm not 100% sure.

**Comment by robbieaverill** [comment]
Ok so the purpose of that `catch` is to ensure that the middleware doesn't break when first creating a DB in the project. If you remove the catch you can see why when you have an empty DB and run a dev/build.

I've made a PR at #389 to be more selective with this so that we can continue request delegation when there's no DB available (skip the middleware's work) but still throw the exception when other errors occur.

**Comment by lekoala** [comment]
that looks good and will certainly help not scratching my head when looking at a page without any error on it :-)
