### ISSUE TITLE
Copying a blocks page to a subsite does not copy blocks

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-subsites#393]
Using `dnadesign/silverstripe-elemental  4.x-dev 4aee187`

If a blocks page includes draft/saved/published blocks, when copying to the page to a subsite through 'Subsite Operations' function, the expected result is the page and the containing blocks are copied to the subsite. Current behaviour copies the page but does not include the saved/published blocks.

Comment from @robbieaverill 
>We probably need to implement recursive duplication. I think subsites has some of its own logic for duplicating across subsites, I refactored some of it recently. It should be using the recursive duplication logic from core as much as possible though. It's also possible that this is fixed with an unreleased version of subsites, need to check.

>Also I think this would be a subsites fix (when we treat elements as arbitrary examples of related models), so we could move this to subsites if you want to @brynwhyman ?

**Comment by sminnee** [comment]
Underlying issue is that `duplicateToSubsite()` doesn't respect `cascade_duplicates`, it instead has its own setting `duplicate_to_subsite_relations`

Two possible solutions:

 * Add `duplicate_to_subsite_relations` config in the elemental module
 * Update `duplicateToSubsite()` to respect cascade_duplicates.

https://github.com/silverstripe/silverstripe-subsites/blob/master/src/Extensions/SiteTreeSubsites.php#L242

**Comment by NightJar** [comment]
Option 2 is the better approach :)

**Comment by robbieaverill** [comment]
Worth noting that we've deprecated `duplciateSubsiteRelations` in favour of the cascade duplicates API already.

I actually can't reproduce this issue using SilverStripe 4.4.x-dev, Subsites 2.3.x-dev and Elemental 4.1.x-dev

**Comment by robbieaverill** [comment]
Yeah, confirmed this is working in the above modules
