### ISSUE TITLE
Unique urls enforced across sites

### ISSUE THREAD

**Issue by tazzydemon** [silverstripe/silverstripe-subsites#53]
Have been swapping between the tractorcow repo and this plus I am using the new Multilingual plugin from kreationsbyran.se. I am therefore in at the deep end so to speak 

However I have noticed that the subsites module does not override the built-in requirement to have unique urls. Therefore across domains it is the same, i.e

domain1.com/home
domain2.com/home is forced to be domain2.com.home-2

IMHO This is not the behaviour that would be expected.

**Comment by tractorcow** [comment]
This doesn't fix the issue properly, so I've re-opened.

This only fixes the issue where the page being saved is in the current subsite. If the page belongs to another subsite, then it will (mistakenly) be filtered in the current subsite.

The correct fix is to implement augmentValidURLSegment() and to check it manually.

In framework 4.x we have the concept of "inheritable" query parameters; We can probably update the root SiteTree::validateURLSegment method so that it inherits these parameters (including subsite) from the parent object being checked.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-subsites/pull/247
